### ISSUE TITLE
DSC/Configuration page lists nothing but the single line of code and the parameters; all other details appear to be placeholders

### ISSUE THREAD

**Issue by rsargentcdw** [MicrosoftDocs/PowerShell-Docs-DSC#58] opened 2022-05-04 16:37 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell DSC I am using.

### Version

2.0

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/configuration?view=dsc-2.0

### Description of the documentation error

The title line says it all; the DSC/Configuration page lists nothing but the single line of code and the parameters; all other details appear to be placeholders.

### Suggested fix

Fill in documentation outside of the placeholder values used for new pages prior to editing.

**Comment by sdwheeler** [comment] 2022-05-04 18:02
Duplicate of #53

**Closed by sdwheeler** 2022-05-04 18:02 UTC
Labels: doc-bug, needs-triage
