### ISSUE TITLE
'Environment' provider changes don't apply to CMD.EXE or PowerShell until the computer restarts

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/PowerShell-Docs-DSC#30] opened 2022-01-02 10:20 UTC
The example works - you can use it, the value will appear in "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" and SystemPropertiesAdvanced.exe will show the environment value is present/absent [as per the DSC policy], but if you check for the environment variable by opening a new command prompt window or starting a new PowerShell process, the change will not apply (if you removed it via DSC, it's still there; if you added it via DSC, it's not there).  It does appear in those locations after a restart.

This is the most stupid idiotic implementation ever.

SETX.EXE works fine.  Whatever method PowerShell is using isn't doing what SETX does.  you must tell your readers that if they try your examples, then don't work the way any IT professional would expect them to work.

This applies to both modules that have the 'ENVIRONMENT' provider.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 702922ad-7b71-6dd0-37ee-9efad626ad9f
* Version Independent ID: 60157828-986c-43e3-a151-9ed69ebdddd7
* Content: [Get started with Desired State Configuration (DSC) for Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/dsc/getting-started/wingettingstarted?view=dsc-1.1)
* Content Source: [dsc/docs-conceptual/dsc-1.1/getting-started/winGettingStarted.md](https://github.com/MicrosoftDocs/PowerShell-Docs-DSC/blob/main/dsc/docs-conceptual/dsc-1.1/getting-started/winGettingStarted.md)
* Product: **powershell**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by michaeltlombardi** [comment] 2022-03-28 20:42
@anwarmahmood1 thanks for reaching out! I can't reproduce your issue. Here are my repro steps:

## Repro Steps
First, verify that the registry key is not set and the environment variable is not available:

```powershell
$env:foo
Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\' -Name foo
```

```text

Get-ItemProperty : Property foo does not exist at path HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\.
At line:1 char:1
+ Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Mana ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (foo:String) [Get-ItemProperty], PSArgumentException
    + FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.GetItemPropertyCommand
```

Next, import the PSDesiredStateConfiguration module and set up a convenient variable so we don't have to type so much:

```powershell
Import-Module -Name PSDesiredStateConfiguration -RequiredVersion 1.1
$SharedParameters = @{
    Name = 'Environment'
    ModuleName = @{
        ModuleName = 'PSDesiredStateConfiguration'
        RequiredVersion = '1.1'
    }
}
```

Now we can run `Invoke-DscResource`, see that the environment variable is not set.

```powershell
Invoke-DscResource @SharedParameters -Method Get -Property @{ Name = 'foo' }
```
```text
ConfigurationName    :                                                                                                      DependsOn            :                                                                                                      ModuleName           : PSDesiredStateConfiguration                                                                          ModuleVersion        : 1.1                                                                                                  PsDscRunAsCredential :                                                                                                      ResourceId           :
SourceInfo           :
Ensure               : Absent
Name                 : foo
Path                 :
Value                :
PSComputerName       : localhost
```

Now we can set the resource and check it again:

```powershell
Invoke-DscResource @SharedParameters -Method Set -Property @{
    Name = 'foo'
    Ensure = 'Present'
    Value = 'bar'
}

Invoke-DscResource @SharedParameters -Method Get -Property @{ Name = 'foo' }
```
```text
RebootRequired
--------------
False

ConfigurationName    :
DependsOn            :
ModuleName           : PSDesiredStateConfiguration
ModuleVersion        : 1.1
PsDscRunAsCredential :
ResourceId           :
SourceInfo           :
Ensure               : Present
Name                 : foo
Path                 :
Value                : bar
PSComputerName       : localhost
```

Now that DSC says it has updated the registry, we can check for ourselves outside of DSC:

```powershell
Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\' -Name foo
```
```text
foo          : bar
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager
PSChildName  : Environment
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry
```

Now, if you check the environment variable at this point, it's not set.
```powershell
$null -eq $env:foo
```
```text
True
```

In order to get the environment variable to load for PowerShell now, you have to either close all of your terminal windows and open a new one or [use the `System.Environment` methods](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_environment_variables#using-systemenvironment-methods) (included here for convenience):

```powershell
[environment]::GetEnvironmentVariable('foo', 'Machine')
$env:foo = [environment]::GetEnvironmentVariable('foo', 'Machine')
$env:foo
```
```text
bar

bar
```

On my machine, closing out of all of my terminals and opening a new terminal also loaded the environment variable.

## Summary

The resource is working as intended; it is modifying the _system_ to change which environment variables will be loaded. When those environment variables take effect and how the process knows that they've been updated is always specific to the process. If you need to change the environment variable for a single process or the current workflow, it's best to do that imperatively, rather than declaratively with DSC.

I'm closing this issue for now; if you're able to send more detailed reproduction steps and information, you might have found a bug which can be reported as such, but the documentation is accurate and the resource is behaving as expected and advertised.

**Closed by michaeltlombardi** 2022-03-28 20:42 UTC
Labels: product-feedback
